"""create queue failed jobs table

Revision ID: c90c9d934260
Revises:
Create Date: 2026-09-04 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c90c9d934260"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_failed_jobs",
        sa.Column("failure_id", sa.String(length=36), nullable=False, comment="失败记录 ID"),
        sa.Column("job_id", sa.String(length=36), nullable=True, comment="原任务 ID，非法信封时为空"),
        sa.Column("payload", sa.LargeBinary().with_variant(mysql.LONGBLOB(), "mysql"), nullable=False, comment="原始任务信封"),
        sa.Column("connection", sa.String(length=200), nullable=False, comment="队列连接名"),
        sa.Column("queue", sa.String(length=200), nullable=False, comment="逻辑队列名"),
        sa.Column("failed_at", sa.DateTime(), nullable=False, comment="最终失败时间"),
        sa.Column("attempts", sa.Integer(), nullable=False, comment="本次投递执行次数"),
        sa.Column("reason", sa.String(length=200), nullable=False, comment="失败原因分类"),
        sa.PrimaryKeyConstraint("failure_id", name=op.f("pk_queue_failed_jobs")),
        comment="队列失败任务记录",
    )
    op.create_index(op.f("ix_queue_failed_jobs_failed_at"), "queue_failed_jobs", ["failed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queue_failed_jobs")
    # ### end Alembic commands ###
