"""create users table

Revision ID: ce3fd8549504
Revises: 
Create Date: 2026-08-28 15:07:35.216041

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


from app.infrastructure.database.orm.main import main_table_name

# revision identifiers, used by Alembic.
revision: str = 'ce3fd8549504'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def table_name(name: str) -> str:
    """根据当前 main 连接配置构建迁移使用的物理表名。"""
    return main_table_name(name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f('ck_x_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_x_users')),
    sa.UniqueConstraint('email', name=op.f('uq_x_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_x_users_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x_users')
    # ### end Alembic commands ###
