"""create user sessions table

Revision ID: 4c7ca5ba7a1d
Revises: 38d220220aa1
Create Date: 2026-09-06 14:04:19.362286

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c7ca5ba7a1d"
down_revision: str | Sequence[str] | None = "38d220220aa1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("token_digest", sa.String(length=64), nullable=False, comment="令牌 SHA-256 摘要"),
        sa.Column("user_id", sa.String(length=36), nullable=False, comment="用户 ID"),
        sa.Column("issued_at", sa.DateTime(), nullable=False, comment="签发时间"),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="过期时间"),
        sa.CheckConstraint("expires_at > issued_at", name=op.f("ck_user_sessions_time_range")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_digest", name=op.f("pk_user_sessions")),
        comment="用户登录会话",
    )
    op.create_index(op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
