from typing import Protocol

from app.contexts.user.domain.user import User
from app.contexts.user.domain.values import EmailAddress, UserId, Username


class UserRepository(Protocol):
    """用户聚合持久化契约。"""

    async def find(self, user_id: UserId) -> User | None: ...

    async def exists_by_username(self, username: Username, *, excluding: UserId | None = None) -> bool: ...

    async def exists_by_email(self, email: EmailAddress, *, excluding: UserId | None = None) -> bool: ...

    async def find_page(self, *, offset: int, limit: int) -> tuple[list[User], int]: ...

    async def add(self, user: User) -> None: ...

    async def update(self, user: User) -> bool: ...

    async def remove(self, user_id: UserId) -> bool: ...
