from typing import Protocol


class Delivery(Protocol):
    @property
    def payload(self) -> bytes: ...
    @property
    def identity(self) -> str: ...
    async def acknowledge(self) -> None: ...


class QueueConsumer(Protocol):
    async def receive(self) -> Delivery: ...
    async def aclose(self) -> None: ...
